export enum codeError{
    EST1 = "Required",
    EST2 = "Not a number",
    EST3 = "Character length must not be greater than",
    EST4 = "Character length must not be less than 3",
    EST5 = "Character length is within",
    EST6 = "Not format",
    EST7 = "Not format phone number",
    EST8 = "Not format email",
    EST9 = "Does not contain special characters",
    EST10 = "The field cannot contain numbers",
    EST11 = "Not format a uuid",
    EST12 = "Not format a base 64",

    ED1 = "Required",
    ED2 = "Not a date",
    ED3 = "Must not be greater than", 
    ED4 = "Must not be less than" ,
    ED5 = "Time in the range",

    ENB1 = "Required",
    ENB2 = "Not a number",
    ENB3 = "Must be greater than", 
    ENB4 = "Must be less than" ,
    ENB5 = "Time in the range",

    EAR1 = "Required",
    EAR2 = "Not a Array",
    EAR3 = "List cannot be greater than ",
    EAR4 = "List cannot be less than ",
    EAR5 = "List in the range",
    EAR6 = "the list contains only numbers",
    EAR7 = "the list contains only strings",
    EAR8 = "the list contains only uuid",
}